server:
  port: 8009
  servlet:
    context-path: /
    schema: https
    redirectport: 8443
    secure: true
    allowtrace: false
spring:
  datasource:
    username: externaluser
    password: externalPass&01
    url: jdbc:mysql://192.168.133.129:3306/weblogdb
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:/sql/*.xml