server:
  port: 8090
  servlet: 
    context-path: /blog/
tomcat: 
  document-root: /wwwroot/document
  ajp: 
    port: 8009
    remoteauthentication: false
spring:
  data:
    rest:
      base-path: /api
  datasource:
    username: externaluser
    password: externalPass&01
    url: jdbc:mysql://192.168.2.122:3306/weblogdb
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:/sql/*.xml